server:
  port: ${PORT:8090}

spring:
  profiles:
    default: local
  config:
    import: optional:file:/etc/secrets/application-prod.yml
  application:
    name: notification-service
  kafka:
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
      security:
        protocol: SSL

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  kafka:
    topic:
      sso-action-events: sso.action.event
      order-status-events: order.status.events
    consumer:
      sso-action-group-id: notification-service-sso-action
      order-status-group-id: notification-service-order-status
